#!/bin/sh -ex
set -o noclobber
VERSION="${VERSION:-$(curl -s https://github.com/helm/helm/releases/latest -w '%{redirect_url}' | sed 's#https://.*/tag/##')}"
cd "$(mktemp -d)"
trap "rm -r $PWD" EXIT
curl -Ls "https://get.helm.sh/helm-${VERSION}-linux-amd64.tar.gz" | tar xvz --strip-components=1
mkdir -p /usr/local/bin /usr/local/share/doc/helm
mv -v helm /usr/local/bin/
mv -v README.md LICENSE /usr/local/share/doc/helm/
