#!/bin/sh -ex
set -o noclobber
VERSION="${VERSION:-$(curl -s https://github.com/kubernetes/kompose/releases/latest -w '%{redirect_url}' | sed 's#https://.*/tag/##')}"
cd "$(mktemp -d)"
trap "rm -r $PWD" EXIT
curl -L https://github.com/kubernetes/kompose/releases/download/$VERSION/kompose-linux-amd64 -o kompose
mkdir -p /usr/local/bin
chmod +x kompose
mv kompose /usr/local/bin/
