#!/bin/sh -ex
set -o noclobber
DESTDIR="${DESTDIR:-/usr/local/bin}"
VERSION="${VERSION:-$(curl -s https://github.com/jesseduffield/lazygit/releases/latest -w '%{redirect_url}' | sed 's#https://.*/tag/##')}"
cd "$(mktemp -d)"
trap "rm -r $PWD" EXIT
curl -Ls "https://github.com/jesseduffield/lazygit/releases/download/${VERSION}/lazygit_${VERSION#v}_Linux_x86_64.tar.gz" | tar xz
mkdir -p ${DESTDIR}
cp lazygit ${DESTDIR}
