#!/bin/sh -ex
set -o noclobber
ARCH=x86_64
VERSION="${VERSION:-$(curl -s https://github.com/jesseduffield/lazydocker/releases/latest -w '%{redirect_url}' | sed 's#https://.*/tag/##')}"
cd "$(mktemp -d)"
trap "rm -r $PWD" EXIT
curl -Ls "https://github.com/jesseduffield/lazydocker/releases/download/$VERSION/lazydocker_${VERSION:1}_Linux_$ARCH.tar.gz" | tar xz
mkdir -p /usr/local/bin /usr/local/share/doc/lazydocker
chmod 755 lazydocker
chmod 644 README.md LICENSE
mv lazydocker /usr/local/bin/
mv README.md LICENSE /usr/local/share/doc/lazydocker/
