#!/bin/sh -ex
set -o noclobber
VERSION="${VERSION:-$(curl -s https://github.com/nushell/nushell/releases/latest -w '%{redirect_url}' | sed 's#https://.*/tag/##')}"
#cd "$(mktemp -d)"
#trap "rm -r $PWD" EXIT
curl -Ls "https://github.com/nushell/nushell/releases/download/${VERSION}/nu-${VERSION}-x86_64-unknown-linux-gnu.tar.gz" | tar xvz --strip-components=1
mv nu /usr/local/bin
