#!/bin/sh -ex
set -o noclobber
VERSION="${VERSION:-$(curl -s https://github.com/cli-tools/postmany/releases/latest -w '%{redirect_url}' | sed 's#https://.*/tag/##')}"
cd "$(mktemp -d)"
trap "rm -r $PWD" EXIT
curl -o postmany -Ls "https://github.com/cli-tools/postmany/releases/download/${VERSION}/postmany" 
chmod 755 postmany
mkdir -p /usr/local/bin
mv postmany /usr/local/bin/
