#!/bin/sh -ex
set -o noclobber
ARCH=x86_64
VERSION="${VERSION:-$(curl -s https://github.com/VirtusLab/render/releases/latest -w '%{redirect_url}' | sed 's#https://.*/tag/##')}"
cd "$(mktemp -d)"
trap "rm -r $PWD" EXIT
curl -LOs "https://github.com/VirtusLab/render/releases/download/$VERSION/render-linux-amd64"
mkdir -p /usr/local/bin
install render-linux-amd64 /usr/local/bin/render
