#!/bin/sh -ex
set -o noclobber
VERSION="${VERSION:-$(curl -s https://github.com/rootless-containers/rootlesskit/releases/latest -w '%{redirect_url}' | sed 's#https://.*/tag/##')}"
cd "$(mktemp -d)"
trap "rm -r $PWD" EXIT
curl -Ls "https://github.com/rootless-containers/rootlesskit/releases/download/${VERSION}/rootlesskit-x86_64.tar.gz" | tar xvz
mkdir -p /usr/local/bin
mv -v ./* /usr/local/bin/
