#!/bin/sh -ex
set -o noclobber
VERSION="${VERSION:-$(curl -s https://github.com/zellij-org/zellij/releases/latest -w '%{redirect_url}' | sed 's#https://.*/tag/##')}"
cd "$(mktemp -d)"
trap "rm -r $PWD" EXIT
curl -Ls "https://github.com/zellij-org/zellij/releases/download/${VERSION}/zellij-x86_64-unknown-linux-musl.tar.gz" | tar xvz
chmod 755 zellij
mkdir -p /usr/local/bin
mv zellij /usr/local/bin/
